server:
  port: 9090

spring:
  flyway:
    baselineOnMigrate: true
  jpa:
    show-sql: true
    generate-ddl: true
  application:
    name:  "auto-supplier"
    datasource.hikari: #HikariCP connection Pool
      pool-name: auto-supplier
      connection-timeout: 60000  # Default: 30000 (30 seconds)
      maximum-pool-size: 5

  datasource.platform: hsqldb

  mail:
    host: smtp.gmail.com
    username: shams.tabrez11@gmail.com
    password: kxyupevevtddcbgz
    fromAddress: shamst242@gmail.com
    createUserSubject: Your account is created, change the password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true

auto-supplier:
  cors:
    origins: "*"
