server:
  port: 9090

spring:
  flyway:
    baselineOnMigrate: true
  jpa:
    show-sql: true
    generate-ddl: true
  application:
    name:  "auto-supplier"
    datasource.hikari: #HikariCP connection Pool
      pool-name: auto-supplier
      connection-timeout: 60000  # Default: 30000 (30 seconds)
      maximum-pool-size: 5

  datasource.platform: hsqldb

auto-supplier:
  cors:
    origins: "*"
