CREATE
  TABLE
    PERMISSION (
      ID UUID NOT NULL,
      CREATED_BY_USER VARCHAR(50),
      MODIFIED_BY_USER VARCHAR(50),
      TIME_CREATED TIMESTAMP NOT NULL,
      TIME_UPDATED TIMESTAMP NOT NULL,
      VERSION BIGINT,
      DESCRIPTION VARCHAR(255),
      UNIQUE_NAME VARCHAR(255) NOT NULL,
      PRIMARY KEY (ID)
);

CREATE
  TABLE
    ROLE (
      ID UUID NOT NULL,
      CREATED_BY_USER VARCHAR(50),
      MODIFIED_BY_USER VARCHAR(50),
      TIME_CREATED TIMESTAMP NOT NULL,
      TIME_UPDATED TIMESTAMP NOT NULL,
      VERSION BIGINT,
      DESCRIPTION VARCHAR(255),
      UNIQUE_NAME VARCHAR(255) NOT NULL,
      PRIMARY KEY (ID)
);

CREATE
  TABLE
    ROLE_PERMISSION (
      ROLE_ID UUID NOT NULL,
      PERMISSION_ID UUID NOT NULL,
      PRIMARY KEY(
        ROLE_ID,
        PERMISSION_ID
      )
    );


CREATE
    TABLE
        SA_USER (
      ID UUID NOT NULL,
      CREATED_BY_USER VARCHAR(50),
      MODIFIED_BY_USER VARCHAR(50),
      TIME_CREATED TIMESTAMP NOT NULL,
      TIME_UPDATED TIMESTAMP NOT NULL,
      VERSION BIGINT,
      USERNAME VARCHAR(50),
      EMAIL VARCHAR(50),
	  FIRST_NAME VARCHAR(50),
	  LAST_NAME VARCHAR(50),
	  PASSWORD VARCHAR(255),
	  ACTIVE INTEGER,
	  PRIMARY KEY (ID)
);

CREATE
  TABLE
    USER_ROLE(
      USER_ID UUID NOT NULL,
      ROLE_ID UUID NOT NULL,
      PRIMARY KEY(
        USER_ID,
        ROLE_ID
      )
    );

CREATE
    TABLE
        RESET_PASSWORD (
      ID UUID NOT NULL,
      CREATED_BY_USER VARCHAR(50),
      MODIFIED_BY_USER VARCHAR(50),
      TIME_CREATED TIMESTAMP NOT NULL,
      TIME_UPDATED TIMESTAMP NOT NULL,
      VERSION BIGINT,
      RESET_TOKEN VARCHAR(255),
      EMAIL VARCHAR(50),
	  PRIMARY KEY (ID)
);

CREATE INDEX IDX_USER_USERNAME ON SA_USER (USERNAME);
CREATE INDEX IDX_USER_EMAIL ON SA_USER (EMAIL);

ALTER TABLE SA_USER
ADD CONSTRAINT UK_USER_USERNAME UNIQUE (USERNAME);

ALTER TABLE SA_USER
ADD CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL);

ALTER TABLE
  ROLE ADD CONSTRAINT UK_ROLE_UNIQUE_NAME UNIQUE(UNIQUE_NAME);

ALTER TABLE
  PERMISSION ADD CONSTRAINT UK_PERMISSION_UNIQUE_NAME UNIQUE(UNIQUE_NAME);

ALTER TABLE
  ROLE_PERMISSION ADD CONSTRAINT FKA6JX8N8XKESMJMV6JQUG6BG68 FOREIGN KEY(ROLE_ID) REFERENCES ROLE;

ALTER TABLE
  ROLE_PERMISSION ADD CONSTRAINT FKF8YLLW1ECVWQY3EHYXAWQA1QP FOREIGN KEY(PERMISSION_ID) REFERENCES PERMISSION;

ALTER TABLE
  USER_ROLE ADD CONSTRAINT FKA68196081FVOVJHKEK5M97N3Y FOREIGN KEY(ROLE_ID) REFERENCES ROLE;

ALTER TABLE
  USER_ROLE ADD CONSTRAINT FK859N2JVI8IVHUI0RL0ESWS6O FOREIGN KEY(USER_ID) REFERENCES SA_USER;
