-- create user permissions
INSERT INTO PERMISSION (ID, UNIQUE_NAME, DESCRIPTION, VERSION, CREATED_BY_USER, MODIFIED_BY_USER, TIME_CREATED, TIME_UPDATED) VALUES ('4781E7D9752D4D35B9DAD157ED2574FF', 'CREATE_USER', 'Create user', 0, NULL, NULL, SYSDATE, SYSDATE);
