CREATE TABLE SA_USER (
      ID UUID PRIMARY KEY,
      CREATED_BY_USER VARCHAR(50),
      MODIFIED_BY_USER VARCHAR(50),
      TIME_CREATED TIMESTAMP NOT NULL,
      TIME_UPDATED TIMESTAMP NOT NULL,
      VERSION BIGINT,
      USERNAME VARCHAR(50),
	  FIRST_NAME VARCHAR(50),
	  LAST_NAME VARCHAR(50),
	  PASSWORD VARCHAR(100),
	  ACTIVE INTEGER
);
